# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "dev-yakuza"
email: "dev.yakuza@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  『Programming Artist ヤクザ』
baseurl: # the subpath of your site, e.g. /blog
url: https://dev-yakuza.posstree.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: # twitter user name
github_username: dev-yakuza
author: dev.yakuza@gmail.com
logo: https://dev-yakuza.posstree.com/assets/images/icon.jpg

# Build settings
# markdown: kramdown
markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]
plugins:
  - jekyll-commonmark
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-polyglot
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-compress-images

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - bin
  - config.rb
  - Gemfile
  - Gemfile.lock
  - gems
  - Procfile
  - Rakefile
  - README.md
  - script
  - vendor
  - .ruby-version
  - Guardfile
  - .jekyll-assets-cache
  - .sass-cache
  - .editorconfig
  - .idea
  - .ruby-version
  - .asset-cache
  - .jekyll-cache
  - change_image_path.py
  - remove_space_href.py
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# pagination
permalink: /:year/:month/
pagination:
  enabled: true
  per_page: 12
  sort_reverse: true
  sort_field: "date"
  title: ":title"
  trail:
    before: 2
    after: 2

# multilang
languages: ["ja", "ko", "en"]
default_lang: "ja"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

# jekyll-compress-image
compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"

jekyll-minifier:
  remove_intertag_spaces: true
  remove_spaces_inside_tags: true
